version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.5.1
    container_name: logstash
    ports:
      - 5044:5044
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch

